# version: "3"

services:
    db:
        image: postgres
        restart: no 
        ports:
            - '${POSTGRES_PORT_HOST}:${POSTGRES_PORT_DOCKER}'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    test-db:
        image: postgres
        restart: no 
        ports:
            - '${POSTGRES_PORT_HOST_TEST}:${POSTGRES_PORT_DOCKER}'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
