# version: "3"

services:
    db:
        image: postgres
        restart: no 
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
